### ISSUE TITLE
How can i use ssh to connect the vm

### ISSUE THREAD

**Issue by Jackkakaya** [KhaosT/ACVM#15]
I use it to install linux and i want ssh it.what can i do? thanks!

**Comment by MichelDiz** [comment]
The qemu bin has a network and for sure it is shared with the host. You should look up for it and check what are the DHCP configs.

Another way is creating an HTTP Tunnel or VPN.

**Comment by bon77** [comment]
You can forward port 22 to your host system. For example to forward ssh to port 2222 on your host add the following to the NIC option field:
`hostfwd=tcp::2222-:22`

Then access your virtual host with
`ssh -p2222 localhost`

**Comment by Jackkakaya** [comment]
thanks!
