### ISSUE TITLE
Wifi in Windows 10

### ISSUE THREAD

**Issue by wkienc** [KhaosT/ACVM#25]
Hi, I am new. I have just installed ACVM with Windows 10 on M1 MacBook Pro. However, I am unable to detect or use wifi in Windows. Downloaded virtio-win-0.1.190.iso it gives an error during installation. " Ended Prematurely"
Any ideas?
<img width="912" alt="Screenshot 2021-01-29 at 12 48 47" src="https://user-images.githubusercontent.com/22675957/106233061-99031380-6230-11eb-908a-1e0ece963896.png">
<img width="912" alt="Screenshot 2021-01-29 at 12 48 51" src="https://user-images.githubusercontent.com/22675957/106233075-9e605e00-6230-11eb-88ec-b6845eb49d3d.png">
<img width="912" alt="Screenshot 2021-01-29 at 12 49 11" src="https://user-images.githubusercontent.com/22675957/106233076-a02a2180-6230-11eb-81b4-2cee95487016.png">

**Comment by KhaosT** [comment]
I think you selected the wrong thing to install. There is an arm64 driver you should install.
