### ISSUE TITLE
 How did you get  "-cpu", "host"

### ISSUE THREAD

**Issue by shareefalis** [KhaosT/ACVM#3]
Did you modify the sources to include cpu type?

Right now i'm getting this using compiled qemu sources: `qemu-system-aarch64: unable to find CPU model 'host'`

https://github.com/KhaosT/ACVM/blob/2473b542613de2b3c79a7ae97a55b3def03c3274/ACVM/ViewController.swift#L96

**Comment by KhaosT** [comment]
Yeah, I added the patch to support `host` option for hvf.
https://github.com/KhaosT/qemu/commit/947aea7a1330d293e0612ea9bff55e5951c5e867

**Comment by shareefalis** [comment]
Thanks, maybe you should fold that back to mailing list as part of the v2 patchset..

**Comment by KhaosT** [comment]
Yeah, probably after the primary patch getting merged?
