### ISSUE TITLE
App permisions required for opening the app

### ISSUE THREAD

**Issue by AdityaJS12321** [KhaosT/ACVM#36]
The app doesnt open and macOS says, "You dont have permission to open the app".

The xcode build only lets me open the app, and nothing happens when i click start after selecting the .vhdk file

**Comment by devBabinski** [comment]
Same here

**Comment by KhaosT** [comment]
Yeah the signing certificate used by this app got revoked by Apple. You'll have to manually resign the qemu related binaries and libraries.
