### ISSUE TITLE
ACVM stopped working Macbook M1 big sur

### ISSUE THREAD

**Issue by neilujyorel** [KhaosT/ACVM#38]
Hi,

I have been using ACVM for the last two weeks on big sure M1 macbook, and out of the sudden I am not able to open it. I have tried all the tricks I could find on internet but nothing works. Any idea on how to fix it?

thanks

![Screen Shot 2021-07-22 at 12 20 01 pm](https://user-images.githubusercontent.com/87791516/126583668-350ab3c2-e8c9-4bbf-aba8-561faa9ef7d9.png)

**Comment by KhaosT** [comment]
Hi,
Apple recently revoked my signing certificate for the app, so the app can no longer be run on the Mac.

You can try to install UTM (https://apps.apple.com/us/app/utm-virtual-machines/id1538878817?mt=12) and use that instead. It's using the same technology behind the scene.

**Comment by neilujyorel** [comment]
UTM is not as good , some issues with the mouse disappearing whatever I tried.
Any way we can get around to unlock ACVM?

Thanks

**Comment by KhaosT** [comment]
@neilujyorel if you have Xcode on your computer, you can clone the latest and build on your computer, that should still work.

**Comment by georgesnow** [comment]
You should be able to use your own certificate  to locally sign the build for your mac
