### ISSUE TITLE
"ACVM" will damage your computer. You should move it to the Bin.

### ISSUE THREAD

**Issue by jamesmortensen** [KhaosT/ACVM#39]
Is there a signing issue with the ACVM.zip file?  When I download it, Mac OS complains that it is infected with malware.  I downloaded it from https://github.com/KhaosT/ACVM/releases/download/v1.0-4/ACVM.zip.

<img width="342" alt="Screenshot 2021-07-27 at 9 23 30 AM" src="https://user-images.githubusercontent.com/1315816/127093157-a8b15b65-5e2e-419a-a7dd-c84001579329.png">

I'm running Macbook Pro M1.  Big Sur 11.4

**Comment by Jyuvv** [comment]
same problem

**Comment by Indiance** [comment]
Same here

**Comment by ghost** [comment]
same here

**Comment by ghost** [comment]
> Is there a signing issue with the ACVM.zip file? When I download it, Mac OS complains that it is infected with malware. I downloaded it from https://github.com/KhaosT/ACVM/releases/download/v1.0-4/ACVM.zip.
> 
> <img alt="Screenshot 2021-07-27 at 9 23 30 AM" width="342" src="https://user-images.githubusercontent.com/1315816/127093157-a8b15b65-5e2e-419a-a7dd-c84001579329.png">
> 
> I'm running Macbook Pro M1. Big Sur 11.4

right click, then go to get info, then override malware protection. @jamesmortensen

**Comment by KhaosT** [comment]
Yeah, Apple revoked the signing certificate so the pre-built binary is no longer valid. If you need this, you can try to build and run with Xcode.

**Comment by shonubijerry** [comment]
Right click on the file, select "Get Info" and check "Override Malware Protection"

<img width="259" alt="Screenshot 2023-09-05 at 15 58 58" src="https://github.com/KhaosT/ACVM/assets/48513215/cd5de9a9-15d8-4c2c-9439-0633f8892037">
