### ISSUE TITLE
Audio Driver

### ISSUE THREAD

**Issue by SIDmao** [KhaosT/ACVM#4]
大佬能不能把这两条加进去
好像是和声卡驱动有关的
反正我加到代码里build后speaker图标就不是禁用状态了
试了下可以发声
```
-device intel-hda 
-device hda-duplex
```

**Comment by shareefalis** [comment]
I will take care of this in an upcoming patch

**Comment by KhaosT** [comment]
Addressed by @shareefalis's PR :)
