### ISSUE TITLE
Can't find ACVM.zip as directed by most tutorials

### ISSUE THREAD

**Issue by deborahtrez** [KhaosT/ACVM#42]
im trying to download the ACVM zip file but all I see is the source code zip files. I want to install ACVM on Mac M1. I find it strange that other people could access the ACVM.zip but I don't see it here. Is the application in here somewhere?

![image](https://user-images.githubusercontent.com/28389950/131127852-468672c3-8834-4904-abe4-e12aea9022ef.png)

**Comment by KhaosT** [comment]
Hi, unfortunately the developer ID certificate was revoked, I wasn't able to build the app and distribute the binary at this point. If you need this app, please manually build it with Xcode.
