### ISSUE TITLE
no binary releases?

### ISSUE THREAD

**Issue by mjonsson1986** [KhaosT/ACVM#45]
are there no binary releases? i found some guides about acvm.  sasys i should download acvm and load it. but no binary releases only sourcecode

**Comment by fragtion** [comment]
same issue here. no builds for the latest release it seems

**Comment by KhaosT** [comment]
Unfortunately I no longer have ability to sign binaries (thanks Apple) so I stopped building them.

**Comment by mjonsson1986** [comment]
We have to use utm  Skickades från E-post för Windows Från: Khaos TianSkickat: den 8 december 2021 03:25Till: KhaosT/ACVMKopia: mjonsson1986; AuthorÄmne: Re: [KhaosT/ACVM] no binary releases? (Issue #45) Unfortunately I no longer have ability to sign binaries (thanks Apple) so I stopped building them.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mjonsson1986** [comment]
No ability to sign binariesSounds like a bad excusesO we should go with utmutm dont have such bad excusesSkickades från E-post för Windows Från: Khaos TianSkickat: den 8 december 2021 03:25Till: KhaosT/ACVMKopia: mjonsson1986; AuthorÄmne: Re: [KhaosT/ACVM] no binary releases? (Issue #45) Unfortunately I no longer have ability to sign binaries (thanks Apple) so I stopped building them.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fragtion** [comment]
Thanks for explanation.  So only alternative is to build from source? Seems a bit far fetched. Why this new limitation and how does other software get around it in order to provide users with built binaries? Thanks

**Comment by georgesnow** [comment]
My understanding is Apple revoked the certificate. And Without that a developer can't offer pre built binaries that will work for others.

**Comment by fragtion** [comment]
How do other developers for other projects manage to do it? I'm guessing it needs to be published to the store? What's the catch exactly? I downloaded the latest UTM dmg and that's working fine

**Comment by DarrienG** [comment]
You can create binaries and codesign them using github actions. https://github.com/Apple-Actions/import-codesign-certs

**Comment by mjonsson1986** [comment]
i assume the dev of this project have left it alone
utm are now in beta 3.0
and gues what? a dmg file are avalable

**Comment by KhaosT** [comment]
Yeah I guess go with UTM if you really need a binary image. I’m unable to create distributable dmg files that runs under normal configuration since I’m blocked from Apple Developer Program 😅

**Comment by mjonsson1986** [comment]
only a stupid ignorant dev say so

**Comment by rcarmo** [comment]
Hi there! I sought out this issue just to say that you're perfectly justified in not having binary releases and that you shouldn't let angry, misguided and uncivilized comments discourage you in any way from putting code out there.

Insults have a way of reflecting upon those who cast them...
