### ISSUE TITLE
Ability to create virtual disk

### ISSUE THREAD

**Issue by markkrueg** [KhaosT/ACVM#6]
Adding the ability to easily create a virtual disk would be amazing. Your GUI makes launching Linux distros just as easy as Windows (and this is arguably more useful to a lot of people). But the first thing a Linux user is going to want is a virtual disk so they can install to it and then reboot from that disk.

The normal way to do this right now would be to use qemu-img command line to create an image, and then mount it from the menu. The problem is qemu-img isn’t included in any of the pre-made binaries floating around and is a bit difficult to get compiled.

Thanks for your consideration; and for building this excellent App!

**Comment by gmpalter** [comment]
I haven't used qemu in years. How do I go about booting a Linux distro using this app?

**Comment by makeable** [comment]
You can use dd to create a raw disk image. Then just use that as your "main image". You can then use a CD image and install to the main image (which is presented as an name drive).

n.b. the guest OS must support the NVMe - I had a quick look, and alpine linux detects it fine, but ubuntu server doesn't - maybe you need to pass in a certain boot flag to ubuntu.

**Comment by KhaosT** [comment]
`qemu-img` is now bundled under `ACVM.app/Contents/Resources/qemu-img`

**Comment by zaaxch** [comment]
> You can use dd to create a raw disk image. Then just use that as your "main image". You can then use a CD image and install to the main image (which is presented as an name drive).
> 
> n.b. the guest OS must support the NVMe - I had a quick look, and alpine linux detects it fine, but ubuntu server doesn't - maybe you need to pass in a certain boot flag to ubuntu.

Any idea which other OS's support NVMe?
